name: namer_app
description: Japanese-English dictionary

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.1.2
  sqlite3: ^2.1.0
  path: ^1.9.1
  path_provider: ^2.1.1
  sqlite3_flutter_libs: ^0.5.32
  google_mlkit_digital_ink_recognition: ^0.14.1
  flutter_drawing_board: ^0.9.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/V6.db